/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // defaultSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to define a custom sidebar
  docsSidebar: [
    {
      type: 'doc',
      id: 'getting-started', // The internal path to the Getting Started document
      label: '🚀 Getting Started',
    },
    {
      type: 'category',
      label: '🤖 Clara Assistant',
      link: {
        type: 'doc',
        id: 'assistant/overview',
      },
      items: [
        'assistant/providers-models',
        'assistant/advanced-options',
        'assistant/mcp-tools',
        'assistant/autonomous-agent',
      ],
    },
    {
      type: 'category',
      label: '🖥️ Desktop Widgets',
      link: {
        type: 'generated-index',
        title: 'Desktop Widgets',
        description: 'Learn how to add, configure, and use desktop widgets to enhance your workspace.',
        slug: '/widgets',
      },
      items: [
        'widgets/adding-widgets',
        'widgets/configuring-widgets',
      ],
    },
    {
      type: 'category',
      label: '🛠️ App Creator (Agents)',
      link: {
        type: 'doc',
        id: 'app-creator/introduction',
      },
      items: [
        'app-creator/building-apps',
        'app-creator/managing-apps',
        'app-creator/apps-as-widgets',
      ],
    },
    // Add more items or categories here as needed
  ],
};

module.exports = sidebars;
